### ISSUE TITLE
出现了重叠placeholder

### ISSUE THREAD

**Issue by lypcliuli** [Rain-dew/YLTextView#1]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/12068023/62531736-97dc6a80-b875-11e9-9e48-9af04af966d9.png">

**Comment by lypcliuli** [comment]
出现重影的代码是这么写的 ：
self.describeTV = [[UITextView alloc] initWithFrame:CGRectZero];
    self.describeTV.placeholder = @"请输入故障描述";
    self.describeTV.limitLength = @100;
    self.describeTV.placeholdColor = UIColorFromRGB(0x666666);
    self.describeTV.limitPlaceColor = UIColorFromRGB(0x666666);
    self.describeTV.placeholdFont = [UIFont systemFontOfSize:15*allScale];
    self.describeTV.limitPlaceFont = [UIFont systemFontOfSize:12*allScale];
    self.describeTV.delegate = self;
    self.describeTV.textColor = [UIColor blackColor];
    self.describeTV.layer.masksToBounds = YES;
    self.describeTV.layer.borderWidth = 0.5;
    self.describeTV.layer.borderColor = UIColorFromRGB(0x666666).CGColor;
    self.describeTV.layer.cornerRadius = 5;
    [self.contentView addSubview:self.describeTV];

**Comment by Rain-dew** [comment]
self.describeTV = [[UITextView alloc] initWithFrame:CGRectZero];这里直接指定frame。因为frame在分类中有计算。




| |
zhangyuluios
|
|
邮箱：zhangyuluios@163.com
|

Signature is customized by Netease Mail Master

在2019年08月06日 18:16，下里巴人_liuli 写道：

出现重影的代码是这么写的 ：
self.describeTV = [[UITextView alloc] initWithFrame:CGRectZero];
self.describeTV.placeholder = @"请输入故障描述";
self.describeTV.limitLength = @100;
self.describeTV.placeholdColor = UIColorFromRGB(0x666666);
self.describeTV.limitPlaceColor = UIColorFromRGB(0x666666);
self.describeTV.placeholdFont = [UIFont systemFontOfSize:15allScale];
self.describeTV.limitPlaceFont = [UIFont systemFontOfSize:12allScale];
self.describeTV.delegate = self;
self.describeTV.textColor = [UIColor blackColor];
self.describeTV.layer.masksToBounds = YES;
self.describeTV.layer.borderWidth = 0.5;
self.describeTV.layer.borderColor = UIColorFromRGB(0x666666).CGColor;
self.describeTV.layer.cornerRadius = 5;
[self.contentView addSubview:self.describeTV];
